'use strict';
const path=require('path'),crypto=require('crypto');
const express=require('express'),session=require('express-session'),bcrypt=require('bcryptjs'),helmet=require('helmet');
const {Pool,Client}=require('pg');
const {validateCatalog,publicCatalog,gameById}=require('./lib/game-catalog');
validateCatalog();
const app=express(),pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:undefined});
class PgSessionStore extends session.Store{get(sid,cb){pool.query('SELECT sess FROM web_sessions WHERE sid=$1 AND expire_at>now()',[sid]).then(r=>cb(null,r.rows[0]?.sess||null)).catch(cb)}set(sid,sess,cb){const exp=new Date(Date.now()+(sess.cookie?.maxAge||600000));
pool.query('INSERT INTO web_sessions(sid,sess,expire_at) VALUES($1,$2,$3) ON CONFLICT(sid) DO UPDATE SET sess=EXCLUDED.sess,expire_at=EXCLUDED.expire_at',[sid,sess,exp]).then(()=>cb?.()).catch(cb)}destroy(sid,cb){pool.query('DELETE FROM web_sessions WHERE sid=$1',[sid]).then(()=>cb?.()).catch(cb)}touch(sid,sess,cb){this.set(sid,sess,cb)}}
const PORT=process.env.PORT||3000,IDLE_MS=600000,TIME_ZONE=process.env.TOVIEW_TIME_ZONE||'Asia/Seoul';
function dateInZone(d=new Date()){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:TIME_ZONE,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(d);
const v=Object.fromEntries(parts.map(x=>[x.type,x.value]));
return `${v.year}-${v.month}-${v.day}`;
}
app.set('trust proxy',1);
app.disable('x-powered-by');
if(process.env.NODE_ENV==='production'&&!process.env.SESSION_SECRET)throw new Error('SESSION_SECRET_REQUIRED');
app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'"],styleSrc:["'self'","'unsafe-inline'"],imgSrc:["'self'",'https:','data:'],frameSrc:["'self'",'https://www.youtube.com','https://www.youtube-nocookie.com'],connectSrc:["'self'"],objectSrc:["'none'"],baseUri:["'self'"],frameAncestors:["'self'"]}}}));
app.use(express.json({limit:'128kb'}));
app.use(express.urlencoded({extended:false,limit:'128kb'}));
const rateBuckets=new Map();
function rateLimit(name,limit,windowMs){return(req,res,next)=>{const key=name+':'+(req.ip||req.socket.remoteAddress||'unknown'),now=Date.now();
let b=rateBuckets.get(key);
if(!b||now-b.start>=windowMs)b={start:now,count:0};
b.count++;
rateBuckets.set(key,b);
if(b.count>limit)return res.status(429).json({ok:false,error:{code:'RATE_LIMITED',message:'요청이 너무 많습니다. 잠시 후 다시 시도해 주세요.'}});
next();
};
}
setInterval(()=>{const now=Date.now();
for(const [k,b] of rateBuckets){if(now-b.start>2*60*60*1000)rateBuckets.delete(k);
}},10*60*1000).unref();
function sameOrigin(req,res,next){if(!['POST','PUT','PATCH','DELETE'].includes(req.method))return next();
const origin=req.get('origin');
if(!origin)return next();
try{const u=new URL(origin);
const expected=req.protocol+'://'+req.get('host');
if(u.origin!==expected)return res.status(403).json({ok:false,error:{code:'CSRF_BLOCKED',message:'허용되지 않은 요청입니다.'}});
}catch{return res.status(403).json({ok:false,error:{code:'CSRF_BLOCKED',message:'허용되지 않은 요청입니다.'}});
}next();
}
app.use('/api',sameOrigin);
app.use(session({store:new PgSessionStore(),name:'toview.sid',secret:process.env.SESSION_SECRET||'toview-dev-only-change-me-please-32chars',resave:false,saveUninitialized:false,cookie:{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:IDLE_MS}}));
const passive=['/api/events','/api/games','/api/sports','/api/ads'];
app.use((req,res,next)=>{const s=req.session;
if(!s?.user)return next();
const now=Date.now();
if(s.lastUserActivityAt&&now-s.lastUserActivityAt>IDLE_MS)return s.destroy(()=>{if(req.path.startsWith('/api/'))return res.status(401).json({ok:false,error:{code:'SESSION_EXPIRED',message:'로그인이 만료되었습니다.'}});
return res.redirect('/account.html?reason=auth&next='+encodeURIComponent(req.originalUrl));
});
if(!(req.method==='GET'&&passive.some(p=>req.path.startsWith(p)))){s.lastUserActivityAt=now;
s.cookie.maxAge=IDLE_MS;
}next();
});
const PROTECTED_PAGES=new Set(['/results.html','/pattern.html','/analysis.html','/sports.html','/community.html','/ranking.html','/dashboard.html','/admin.html']);
app.get([...PROTECTED_PAGES],(req,res,next)=>{if(req.session?.user)return next();
const nextPath=req.originalUrl;
return res.redirect('/account.html?reason=auth&next='+encodeURIComponent(nextPath));
});
app.use(express.static(path.join(__dirname,'public'),{extensions:['html']}));
const ok=(res,data,meta)=>res.json({ok:true,data,...(meta?{meta}:{})});
const fail=(res,status,code,message)=>res.status(status).json({ok:false,error:{code,message}});
const auth=(req,res,next)=>req.session?.user?next():fail(res,401,'AUTH_REQUIRED','로그인이 필요합니다.');
const admin=(req,res,next)=>req.session?.user?.role==='admin'?next():fail(res,403,'ADMIN_REQUIRED','관리자 권한이 필요합니다.');
app.post('/api/activity',auth,(req,res)=>ok(res,{active:true}));
app.get('/api/health',(req,res)=>ok(res,{status:'ok',time:new Date().toISOString()}));
app.get('/api/games',(req,res)=>ok(res,publicCatalog()));
app.get('/api/me',(req,res)=>req.session?.user?ok(res,req.session.user):fail(res,401,'AUTH_REQUIRED','로그인이 필요합니다.'));
app.post('/api/login',rateLimit('login',12,10*60*1000),async(req,res)=>{try{const r=await pool.query('SELECT id,username,nickname,email,role,password_hash FROM users WHERE username=$1 LIMIT 1',[String(req.body.username||'').trim()]);
const u=r.rows[0];
if(!u||!(await bcrypt.compare(String(req.body.password||''),u.password_hash)))return fail(res,401,'INVALID_LOGIN','아이디 또는 비밀번호를 확인해 주세요.');
req.session.regenerate(err=>{if(err)return fail(res,500,'SESSION_ERROR','로그인 처리에 실패했습니다.');
req.session.user={id:u.id,username:u.username,nickname:u.nickname,email:u.email,role:u.role};
req.session.lastUserActivityAt=Date.now();
req.session.cookie.maxAge=IDLE_MS;
ok(res,req.session.user);
});
}catch(e){console.error(e);
fail(res,500,'LOGIN_ERROR','로그인 처리에 실패했습니다.');
}});
app.post('/api/logout',(req,res)=>req.session.destroy(()=>ok(res,{loggedOut:true})));
const hasTripleRepeat=s=>/(.)\1\1/i.test(s);
function hasTripleSequence(s){const t=String(s).toLowerCase();
for(let i=0;
i<t.length-2;
i++){const a=t.charCodeAt(i),b=t.charCodeAt(i+1),c=t.charCodeAt(i+2);
if((b===a+1&&c===b+1)||(b===a-1&&c===b-1))return true;
}return false;
}
async function sendVerificationEmail(to,code){
const apiKey=String(process.env.RESEND_API_KEY||'').trim();
const from=String(process.env.RESEND_FROM||process.env.GMAIL_USER||'').trim();
if(!apiKey||!from)return false;
const response=await fetch('https://api.resend.com/emails',{
method:'POST',
headers:{
'Authorization':`Bearer ${apiKey}`,
'Content-Type':'application/json'
},
body:JSON.stringify({
from,
to:[to],
subject:'TOVIEW 이메일 인증번호',
text:`TOVIEW 인증번호는 ${code} 입니다. 10분 안에 입력해 주세요.`
})
});
if(!response.ok){
const detail=await response.text().catch(()=> '');
throw new Error(`RESEND_SEND_FAILED:${response.status}:${detail.slice(0,500)}`);
}
return true;
}
app.post('/api/email/send',rateLimit('email-send',5,10*60*1000),async(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase();
if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return fail(res,400,'INVALID_EMAIL','이메일을 확인해 주세요.');
const exists=await pool.query('SELECT 1 FROM users WHERE email=$1 LIMIT 1',[email]);
if(exists.rowCount)return fail(res,409,'EMAIL_IN_USE','이미 가입된 이메일입니다.');
const code=String(Math.floor(100000+Math.random()*900000)),hash=crypto.createHash('sha256').update(code).digest('hex');
await pool.query("INSERT INTO email_verifications(email,code_hash,expires_at) VALUES($1,$2,now()+interval '10 minutes') ON CONFLICT(email) DO UPDATE SET code_hash=EXCLUDED.code_hash,expires_at=EXCLUDED.expires_at,verified_at=NULL",[email,hash]);
const sent=await sendVerificationEmail(email,code);
if(!sent){if(process.env.NODE_ENV==='production')return fail(res,503,'EMAIL_NOT_CONFIGURED','이메일 인증 서비스가 준비되지 않았습니다.');
console.log('[DEV EMAIL CODE]',email,code);
return ok(res,{sent:true,devCode:code});
}
ok(res,{sent:true});
}catch(e){console.error(e);
fail(res,500,'EMAIL_SEND_ERROR','인증메일 발송에 실패했습니다.');
}});
app.post('/api/email/verify',rateLimit('email-verify',12,10*60*1000),async(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),code=String(req.body.code||'').trim(),hash=crypto.createHash('sha256').update(code).digest('hex');
const r=await pool.query('UPDATE email_verifications SET verified_at=now() WHERE email=$1 AND code_hash=$2 AND expires_at>now() RETURNING email',[email,hash]);
if(!r.rowCount)return fail(res,400,'INVALID_CODE','인증번호가 올바르지 않거나 만료되었습니다.');
req.session.verifiedEmail=email;
ok(res,{verified:true,email});
}catch(e){console.error(e);
fail(res,500,'EMAIL_VERIFY_ERROR','이메일 인증에 실패했습니다.');
}});
app.post('/api/register',rateLimit('register',6,60*60*1000),async(req,res)=>{try{const username=String(req.body.username||'').trim(),nickname=String(req.body.nickname||'').trim(),email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');
if(!/^[A-Za-z]{5,40}$/.test(username)||hasTripleRepeat(username)||hasTripleSequence(username))return fail(res,400,'INVALID_USERNAME','아이디 규칙을 확인해 주세요.');
if(!/^[가-힣]{2,30}$/.test(nickname))return fail(res,400,'INVALID_NICKNAME','닉네임은 한글 2자 이상으로 입력해 주세요.');
if(password.length<8||!/[A-Za-z]/.test(password)||!/\d/.test(password)||hasTripleRepeat(password)||hasTripleSequence(password))return fail(res,400,'INVALID_PASSWORD','비밀번호 규칙을 확인해 주세요.');
if(req.session.verifiedEmail!==email)return fail(res,400,'EMAIL_NOT_VERIFIED','이메일 인증을 완료해 주세요.');
const hash=await bcrypt.hash(password,12);
const r=await pool.query('INSERT INTO users(username,password_hash,nickname,email) VALUES($1,$2,$3,$4) RETURNING id,username,nickname,email,role',[username,hash,nickname,email]);
ok(res,r.rows[0]);
}catch(e){if(e.code==='23505')return fail(res,409,'DUPLICATE_USER','이미 사용 중인 회원정보가 있습니다.');
console.error(e);
fail(res,500,'REGISTER_ERROR','회원가입에 실패했습니다.');
}});
const norm=r=>({resultId:r.result_id,gameId:r.game_id,drawDate:r.draw_date,roundNumber:r.round_number,scheduledAt:r.scheduled_at,status:r.status,result:r.result_json,publishedAt:r.published_at});
app.get('/api/games/snapshot',async(req,res)=>{try{const r=await pool.query('SELECT DISTINCT ON(game_id) * FROM game_results ORDER BY game_id,draw_date DESC,round_number DESC'),m=new Map(r.rows.map(x=>[x.game_id,norm(x)]));
ok(res,publicCatalog().map(g=>({...g,lastResult:m.get(g.id)||null})));
}catch(e){console.error(e);
fail(res,500,'SNAPSHOT_ERROR','게임 정보를 불러오지 못했습니다.');
}});
app.get('/api/games/:id/snapshot',async(req,res)=>{try{const g=gameById(req.params.id);
if(!g)return fail(res,404,'GAME_NOT_FOUND','지원하지 않는 게임입니다.');
const last=await pool.query('SELECT * FROM game_results WHERE game_id=$1 ORDER BY draw_date DESC,round_number DESC LIMIT 1',[g.id]);
const next=await pool.query("SELECT round_id,game_id,draw_date,round_number,scheduled_at,status FROM game_rounds WHERE game_id=$1 AND status='OPEN' ORDER BY scheduled_at DESC LIMIT 1",[g.id]);
ok(res,{game:g,lastResult:last.rowCount?norm(last.rows[0]):null,currentRound:next.rows[0]||null,serverNow:new Date().toISOString()});
}catch(e){console.error(e);
fail(res,500,'GAME_SNAPSHOT_ERROR','게임 상태를 불러오지 못했습니다.');
}});
app.get('/api/games/:id/results',async(req,res)=>{try{const g=gameById(req.params.id);
if(!g)return fail(res,404,'GAME_NOT_FOUND','지원하지 않는 게임입니다.');
const date=String(req.query.date||dateInZone()),limit=Math.min(1000,Math.max(1,Number(req.query.limit)||100));
const r=await pool.query('SELECT * FROM game_results WHERE game_id=$1 AND draw_date=$2 ORDER BY round_number DESC LIMIT $3',[g.id,date,limit]);
ok(res,r.rows.map(norm),{game:g.id,date});
}catch(e){console.error(e);
fail(res,500,'RESULTS_ERROR','결과를 불러오지 못했습니다.');
}});
app.get('/api/games/:id/pattern',async(req,res)=>{try{const g=gameById(req.params.id);
if(!g)return fail(res,404,'GAME_NOT_FOUND','지원하지 않는 게임입니다.');
const date=String(req.query.date||dateInZone());
const r=await pool.query('SELECT * FROM game_results WHERE game_id=$1 AND draw_date=$2 ORDER BY round_number ASC',[g.id,date]);
ok(res,r.rows.map(norm),{game:g.id,date,total:r.rowCount});
}catch(e){console.error(e);
fail(res,500,'PATTERN_ERROR','패턴 데이터를 불러오지 못했습니다.');
}});
app.get('/api/games/:id/analysis',async(req,res)=>{try{const g=gameById(req.params.id);
if(!g)return fail(res,404,'GAME_NOT_FOUND','지원하지 않는 게임입니다.');
const days=Math.min(30,Math.max(1,Number(req.query.days)||1));
const r=await pool.query('SELECT * FROM game_results WHERE game_id=$1 AND draw_date>=CURRENT_DATE-($2::int-1) ORDER BY draw_date,round_number',[g.id,days]);
const rows=r.rows.map(norm),summary={total:rows.length,odd:0,even:0,under:0,over:0};
for(const x of rows){if(x.result?.oddEven==='odd')summary.odd++;
if(x.result?.oddEven==='even')summary.even++;
if(x.result?.underOver==='under')summary.under++;
if(x.result?.underOver==='over')summary.over++;
}ok(res,{summary,records:rows.slice(-200)},{game:g.id,days});
}catch(e){console.error(e);
fail(res,500,'ANALYSIS_ERROR','분석 데이터를 불러오지 못했습니다.');
}});
app.post('/api/picks/mini',auth,async(req,res)=>{const c=await pool.connect();
try{await c.query('BEGIN');
const roundId=Number(req.body.roundId),market=String(req.body.marketType||''),selection=String(req.body.selection||''),visibility=String(req.body.visibility||'FOLLOWERS');
if(!['odd_even','under_over'].includes(market)||!['odd','even','under','over'].includes(selection)||(market==='odd_even'&&!['odd','even'].includes(selection))||(market==='under_over'&&!['under','over'].includes(selection)))throw Object.assign(new Error(),{status:400,code:'BAD_PICK'});
if(!['PUBLIC','FOLLOWERS','MUTUALS','PRIVATE'].includes(visibility))throw Object.assign(new Error(),{status:400,code:'BAD_VISIBILITY'});
const rr=await c.query('SELECT round_id,scheduled_at,status FROM game_rounds WHERE round_id=$1 FOR UPDATE',[roundId]);
if(!rr.rowCount)throw Object.assign(new Error(),{status:404,code:'ROUND_NOT_FOUND'});
if(rr.rows[0].status!=='OPEN'||Date.now()>=new Date(rr.rows[0].scheduled_at).getTime())throw Object.assign(new Error(),{status:409,code:'PICK_CLOSED'});
const r=await c.query('INSERT INTO mini_game_picks(user_id,round_id,market_type,selection,visibility) VALUES($1,$2,$3,$4,$5) RETURNING *',[req.session.user.id,roundId,market,selection,visibility]);
await c.query('COMMIT');
ok(res,r.rows[0]);
}catch(e){await c.query('ROLLBACK');
if(e.code==='23505')return fail(res,409,'PICK_EXISTS','이미 등록한 PICK입니다.');
if(e.status)return fail(res,e.status,e.code,e.code==='PICK_CLOSED'?'PICK 등록이 마감되었습니다.':'PICK을 등록할 수 없습니다.');
console.error(e);
fail(res,500,'PICK_ERROR','PICK 등록에 실패했습니다.');
}finally{c.release();
}});
async function relation(a,b){const bl=await pool.query('SELECT 1 FROM blocks WHERE (blocker_id=$1 AND blocked_id=$2) OR (blocker_id=$2 AND blocked_id=$1) LIMIT 1',[a,b]);
if(bl.rowCount)return {blocked:true,following:false,mutual:false};
const r=await pool.query('SELECT follower_id,following_id FROM follows WHERE (follower_id=$1 AND following_id=$2) OR (follower_id=$2 AND following_id=$1)',[a,b]);
const f=r.rows.some(x=>Number(x.follower_id)===Number(a)&&Number(x.following_id)===Number(b)),rev=r.rows.some(x=>Number(x.follower_id)===Number(b)&&Number(x.following_id)===Number(a));
return {blocked:false,following:f,mutual:f&&rev};
}
async function canViewPick(viewerId,ownerId,visibility){if(Number(viewerId)===Number(ownerId))return true;
if(visibility==='PUBLIC')return true;
if(visibility==='PRIVATE')return false;
const rel=await relation(viewerId,ownerId);
if(rel.blocked)return false;
if(visibility==='FOLLOWERS')return rel.following;
if(visibility==='MUTUALS')return rel.mutual;
return false;
}
app.get('/api/users/:id/picks/mini',auth,async(req,res)=>{try{const owner=Number(req.params.id),r=await pool.query(`SELECT p.pick_id,p.user_id,p.market_type,p.selection,p.visibility,p.verdict,p.created_at,gr.game_id,gr.draw_date,gr.round_number FROM mini_game_picks p JOIN game_rounds gr ON gr.round_id=p.round_id WHERE p.user_id=$1 ORDER BY p.created_at DESC LIMIT 100`,[owner]),out=[];
for(const x of r.rows)if(await canViewPick(req.session.user.id,owner,x.visibility))out.push(x);
ok(res,out);
}catch(e){console.error(e);
fail(res,500,'PICK_FEED_ERROR','PICK을 불러오지 못했습니다.');
}});
app.get('/api/users/:id/picks/sports',auth,async(req,res)=>{try{const owner=Number(req.params.id),r=await pool.query(`SELECT p.pick_id,p.user_id,p.market_type,p.selection,p.visibility,p.verdict,p.created_at,e.event_id,e.home_name,e.away_name,e.start_at,e.status FROM sports_picks p JOIN sports_events e ON e.event_id=p.event_id WHERE p.user_id=$1 ORDER BY p.created_at DESC LIMIT 100`,[owner]),out=[];
for(const x of r.rows)if(await canViewPick(req.session.user.id,owner,x.visibility))out.push(x);
ok(res,out);
}catch(e){console.error(e);
fail(res,500,'SPORTS_PICK_FEED_ERROR','스포츠 PICK을 불러오지 못했습니다.');
}});
app.get('/api/picks/mini/:roundId/stats',auth,async(req,res)=>{try{const r=await pool.query(`SELECT count(*)::int total,count(*) FILTER(WHERE selection='odd')::int odd,count(*) FILTER(WHERE selection='even')::int even,count(*) FILTER(WHERE selection='under')::int under,count(*) FILTER(WHERE selection='over')::int over FROM mini_game_picks WHERE round_id=$1`,[Number(req.params.roundId)]);
ok(res,r.rows[0]);
}catch(e){fail(res,500,'PICK_STATS_ERROR','PICK 통계를 불러오지 못했습니다.');
}});
app.get('/api/picks/sports/:eventId/stats',auth,async(req,res)=>{try{const r=await pool.query(`SELECT count(*)::int total,count(*) FILTER(WHERE selection='HOME')::int home,count(*) FILTER(WHERE selection='DRAW')::int draw,count(*) FILTER(WHERE selection='AWAY')::int away FROM sports_picks WHERE event_id=$1`,[Number(req.params.eventId)]);
ok(res,r.rows[0]);
}catch(e){fail(res,500,'SPORTS_PICK_STATS_ERROR','PICK 통계를 불러오지 못했습니다.');
}});
app.post('/api/follow/:id',auth,async(req,res)=>{try{const id=Number(req.params.id);
if(!Number.isInteger(id)||id<=0||id===Number(req.session.user.id))return fail(res,400,'SELF_FOLLOW','팔로우할 수 없는 회원입니다.');
const exists=await pool.query('SELECT 1 FROM users WHERE id=$1 LIMIT 1',[id]);
if(!exists.rowCount)return fail(res,404,'USER_NOT_FOUND','회원을 찾을 수 없습니다.');
if((await relation(req.session.user.id,id)).blocked)return fail(res,403,'BLOCKED','차단 관계에서는 팔로우할 수 없습니다.');
await pool.query('INSERT INTO follows(follower_id,following_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[req.session.user.id,id]);
ok(res,{following:true});
}catch(e){console.error(e);
fail(res,500,'FOLLOW_ERROR','팔로우 처리에 실패했습니다.');
}});
app.delete('/api/follow/:id',auth,async(req,res)=>{try{const id=Number(req.params.id);
if(!Number.isInteger(id)||id<=0)return fail(res,400,'BAD_USER','회원을 확인해 주세요.');
await pool.query('DELETE FROM follows WHERE follower_id=$1 AND following_id=$2',[req.session.user.id,id]);
ok(res,{following:false});
}catch(e){console.error(e);
fail(res,500,'UNFOLLOW_ERROR','언팔로우 처리에 실패했습니다.');
}});
app.post('/api/block/:id',auth,async(req,res)=>{const id=Number(req.params.id),me=Number(req.session.user.id);
if(!id||id===me)return fail(res,400,'BAD_BLOCK','차단할 수 없는 회원입니다.');
const c=await pool.connect();
try{await c.query('BEGIN');
await c.query('INSERT INTO blocks(blocker_id,blocked_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[me,id]);
await c.query('DELETE FROM follows WHERE (follower_id=$1 AND following_id=$2) OR (follower_id=$2 AND following_id=$1)',[me,id]);
await c.query('COMMIT');
ok(res,{blocked:true});
}catch(e){await c.query('ROLLBACK');
fail(res,500,'BLOCK_ERROR','차단 처리에 실패했습니다.');
}finally{c.release();
}});
app.get('/api/community/posts',auth,async(req,res)=>{try{const board=String(req.query.board||'free');
if(!['notice','free','analysis'].includes(board))return fail(res,400,'BAD_BOARD','게시판을 확인해 주세요.');
const r=await pool.query('SELECT p.*,u.nickname,u.role FROM posts p LEFT JOIN users u ON u.id=p.user_id WHERE board_id=$1 ORDER BY is_pinned DESC,created_at DESC LIMIT 100',[board]);
ok(res,r.rows);
}catch(e){console.error(e);
fail(res,500,'POSTS_ERROR','게시글을 불러오지 못했습니다.');
}});
app.post('/api/community/posts',auth,async(req,res)=>{try{const board=String(req.body.boardId||'free');
if(!['free','analysis'].includes(board)&&req.session.user.role!=='admin')return fail(res,400,'BAD_BOARD','게시판을 확인해 주세요.');
const title=String(req.body.title||'').trim().slice(0,160),body=String(req.body.body||'').trim().slice(0,20000);
if(!title||!body)return fail(res,400,'EMPTY_POST','제목과 내용을 입력해 주세요.');
const r=await pool.query('INSERT INTO posts(user_id,board_id,title,body) VALUES($1,$2,$3,$4) RETURNING *',[req.session.user.id,board,title,body]);
ok(res,r.rows[0]);
}catch(e){console.error(e);
fail(res,500,'POST_ERROR','게시글 등록에 실패했습니다.');
}});
app.get('/api/verified',async(req,res)=>{try{const r=await pool.query('SELECT id,name,status,guarantee_period,last_reviewed_at,rating,url,logo_url FROM verified_partners ORDER BY id DESC');
ok(res,r.rows);
}catch(e){console.error(e);
fail(res,500,'VERIFIED_ERROR','보증업체 정보를 불러오지 못했습니다.');
}});
app.get('/api/ads/:slot',async(req,res)=>{try{const r=await pool.query('SELECT id,advertiser,image_url,mobile_image_url,target_url,weight FROM ad_campaigns WHERE slot_id=$1 AND active=true AND (starts_at IS NULL OR starts_at<=now()) AND (ends_at IS NULL OR ends_at>=now()) ORDER BY random()*GREATEST(weight,1) DESC LIMIT 1',[String(req.params.slot).slice(0,64)]);
ok(res,r.rows[0]||null);
}catch(e){console.error(e);
ok(res,null);
}});
app.get('/go/ad/:id',async(req,res)=>{try{const r=await pool.query('SELECT target_url FROM ad_campaigns WHERE id=$1 AND active=true',[Number(req.params.id)]);
if(!r.rowCount)return res.redirect('/');
const u=new URL(r.rows[0].target_url);
return ['http:','https:'].includes(u.protocol)?res.redirect(u.toString()):res.redirect('/');
}catch{return res.redirect('/');
}});
app.get('/api/sports/events',auth,async(req,res)=>{try{const r=await pool.query('SELECT event_id,name,sport,league,home_name,away_name,start_at,status,home_score,away_score,stream_provider,stream_ref FROM sports_events ORDER BY start_at DESC LIMIT 200');
ok(res,r.rows);
}catch(e){console.error(e);
fail(res,500,'SPORTS_ERROR','스포츠 정보를 불러오지 못했습니다.');
}});
app.post('/api/picks/sports',auth,async(req,res)=>{const c=await pool.connect();
try{await c.query('BEGIN');
const eventId=Number(req.body.eventId),visibility=String(req.body.visibility||'FOLLOWERS');
const market=String(req.body.marketType||'winner'),selection=String(req.body.selection||'');
if(!Number.isInteger(eventId)||eventId<=0||market!=='winner'||!['HOME','DRAW','AWAY'].includes(selection))throw Object.assign(new Error(),{status:400,code:'BAD_PICK'});
if(!['PUBLIC','FOLLOWERS','MUTUALS','PRIVATE'].includes(visibility))throw Object.assign(new Error(),{status:400,code:'BAD_VISIBILITY'});
const e=await c.query('SELECT start_at,status FROM sports_events WHERE event_id=$1 FOR UPDATE',[eventId]);
if(!e.rowCount)throw Object.assign(new Error(),{status:404,code:'EVENT_NOT_FOUND'});
if(['LIVE','FINISHED','CANCELLED'].includes(String(e.rows[0].status).toUpperCase())||Date.now()>=new Date(e.rows[0].start_at).getTime())throw Object.assign(new Error(),{status:409,code:'PICK_CLOSED'});
const r=await c.query('INSERT INTO sports_picks(user_id,event_id,market_type,selection,visibility) VALUES($1,$2,$3,$4,$5) RETURNING *',[req.session.user.id,eventId,market,selection,visibility]);
await c.query('COMMIT');
ok(res,r.rows[0]);
}catch(e){await c.query('ROLLBACK');
if(e.code==='23505')return fail(res,409,'PICK_EXISTS','이미 등록한 PICK입니다.');
if(e.status)return fail(res,e.status,e.code,e.code==='PICK_CLOSED'?'PICK 등록이 마감되었습니다.':'PICK을 등록할 수 없습니다.');
console.error(e);
fail(res,500,'SPORTS_PICK_ERROR','PICK 등록에 실패했습니다.');
}finally{c.release();
}});
const sse=new Set(),sseByIp=new Map();
app.get('/api/events',(req,res)=>{const ip=req.ip||req.socket.remoteAddress||'unknown',n=sseByIp.get(ip)||0;
if(n>=4)return res.status(429).end();
res.set({'Content-Type':'text/event-stream','Cache-Control':'no-cache, no-transform','Connection':'keep-alive','X-Accel-Buffering':'no'});
res.flushHeaders?.();
sse.add(res);
sseByIp.set(ip,n+1);
res.write(`event: snapshot\ndata: ${JSON.stringify({time:Date.now()})}\n\n`);
const k=setInterval(()=>{if(!res.writableEnded)res.write(': keepalive\n\n');
},25000);
const close=()=>{clearInterval(k);
sse.delete(res);
const left=Math.max(0,(sseByIp.get(ip)||1)-1);
left?sseByIp.set(ip,left):sseByIp.delete(ip);
};
req.once('close',close);
res.once('close',close);
res.once('error',close);
});
function broadcast(type,data){for(const res of [...sse]){if(res.writableEnded){sse.delete(res);
continue;
}try{res.write(`event: ${type}\ndata: ${JSON.stringify(data)}\n\n`);
}catch{sse.delete(res);
}}}
let notifyClient=null;
async function startDbListener(){if(!process.env.DATABASE_URL)return;
notifyClient=new Client({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:undefined});
notifyClient.on('error',e=>{console.error('[db-listen]',e.message);
setTimeout(startDbListener,3000).unref?.();
});
await notifyClient.connect();
await notifyClient.query('LISTEN toview_game_result');
notifyClient.on('notification',async msg=>{try{const key=JSON.parse(msg.payload||'{}');
if(!key.gameId||!key.drawDate||!key.roundNumber)return;
const r=await pool.query('SELECT * FROM game_results WHERE game_id=$1 AND draw_date=$2 AND round_number=$3 LIMIT 1',[key.gameId,key.drawDate,key.roundNumber]);
if(r.rowCount)broadcast('game-result',norm(r.rows[0]));
}catch(e){console.error('[game-result-notify]',e.message);
}});
}
startDbListener().catch(e=>console.error('[db-listen-start]',e.message));
app.post('/api/admin/broadcast',admin,(req,res)=>{broadcast('admin-notice',{message:String(req.body.message||'').slice(0,500)});
ok(res,{sent:true});
});
app.get('/api/admin/status',admin,async(req,res)=>{try{const r=await pool.query('SELECT game_id,max(published_at) last_result_at FROM game_results GROUP BY game_id ORDER BY game_id');
ok(res,{games:r.rows,sseClients:sse.size});
}catch(e){fail(res,500,'ADMIN_STATUS_ERROR','상태 조회에 실패했습니다.');
}});
app.use('/api',(req,res)=>fail(res,404,'API_NOT_FOUND','요청한 API가 없습니다.'));
app.listen(PORT,()=>console.log(`TOVIEW listening on ${PORT}`));
module.exports={app,pool,broadcast};
